services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - '44444:3306'
    volumes:
      - ./mysql/db:/var/lib/mysql
    restart: always

networks:
  default:
    name: spring-hibernate
    driver: bridge