### Получить все продукты
GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json

### Получить продукт по ID
GET http://localhost:8080/products/1 HTTP/1.1
Content-Type: application/json

### Создать новый продукт
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
  "name": "New Product",
  "price": 2000.0
}

### Обновить продукт по ID
PUT http://localhost:8080/products/5 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 300.0
}

### Удалить продукт по ID
DELETE http://localhost:8080/products/1 HTTP/1.1
Content-Type: application/json